[package]
name = "calculator"
version = "0.1.0"
authors = ["Kai Devrim <kai@devrim.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
